version: '3.8'

networks:
  vplatform_net:
    driver: bridge

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    networks:
      - vplatform_net
    environment:
      MYSQL_ROOT_PASSWORD: 你的MySQL密码
    # 数据持久化
    volumes:
      - /opt/vplatform/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  flask-app:
    build: .
    networks:
      - vplatform_net
    ports:
      - "22048:22048"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=你的MySQL密码
      - MYSQL_DATABASE=design
      - SECRET_KEY=your_production_secret_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build: ./client
    container_name: nginx-frontend
    restart: always
    networks:
      - vplatform_net
    ports:
      - "808:80"
    depends_on:
      flask-app:
        condition: service_healthy
